# Generated by Django 2.2 on 2021-11-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
