# Generated by Django 3.2.3 on 2022-01-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_privatemessage_id'),
        ('chats', '0002_auto_20220113_1407'),
    ]

    operations = [
    ]
